# Generated by Django 3.0.6 on 2020-05-19 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour_name', models.CharField(max_length=30)),
                ('in_stock', models.BooleanField()),
                ('add_time', models.DateField(verbose_name='date published')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.Manufacturer')),
            ],
        ),
    ]
