# Generated by Django 3.0.6 on 2020-05-22 11:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='flavour',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavours', to='sklad.Manufacturer'),
        ),
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mix_name', models.CharField(max_length=30)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('strength', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('compound', models.ManyToManyField(through='sklad.Membership', to='sklad.Flavour')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='flavour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.Flavour'),
        ),
        migrations.AddField(
            model_name='membership',
            name='mix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.Mix'),
        ),
    ]
