# Generated by Django 3.0.6 on 2020-06-14 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0003_membership_persontage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mixes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mix_name', models.CharField(max_length=30)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('strength', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('compound', models.ManyToManyField(to='sklad.Flavour')),
            ],
        ),
    ]
