# Generated by Django 3.0.6 on 2020-06-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0004_mixes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mixes',
        ),
    ]
