# Generated by Django 3.0.6 on 2020-06-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0005_delete_mixes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='persontage',
            new_name='percentage',
        ),
    ]
