# Generated by Django 3.0.6 on 2020-07-20 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0006_auto_20200615_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='percentage',
            field=models.PositiveIntegerField(default=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
