# Generated by Django 3.0.6 on 2020-07-20 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0007_auto_20200720_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='mix',
            name='rating',
            field=models.PositiveIntegerField(default=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='mix',
            name='strength',
            field=models.PositiveIntegerField(default=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
