# Generated by Django 3.0.6 on 2020-07-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0010_auto_20200729_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='flavour_type',
            field=models.ManyToManyField(to='sklad.FlavourType'),
        ),
    ]
