# Generated by Django 3.0.6 on 2020-08-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0011_auto_20200729_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='type',
            field=models.IntegerField(choices=[(1, 'Tobacco'), (2, 'Tea')], null=True),
        ),
    ]
