# Generated by Django 3.0.6 on 2020-08-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0013_auto_20200815_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='type',
            field=models.CharField(choices=[('TE', 'Tea'), ('TC', 'Tobacco')], max_length=2, null=True),
        ),
    ]
