# Generated by Django 3.1 on 2020-08-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0014_auto_20200815_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='type',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='type',
            field=models.ManyToManyField(to='sklad.ManufacturerType'),
        ),
    ]
