# Generated by Django 3.1 on 2020-09-30 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0016_auto_20200815_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='BowlType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Bowl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklad.bowltype')),
            ],
        ),
        migrations.AddField(
            model_name='mix',
            name='bowl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklad.bowl'),
        ),
    ]
