# Generated by Django 3.1 on 2021-01-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0017_auto_20200930_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavour',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mix',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
