# Generated by Django 3.1 on 2025-02-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0019_auto_20210121_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavour', to='sklad.manufacturer'),
        ),
    ]
